# Generated by Django 4.0.1 on 2022-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='available_balance',
            field=models.FloatField(default=0),
        ),
    ]
