# Generated by Django 4.0.1 on 2022-01-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_loanoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanoffer',
            name='annual_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanoffer',
            name='loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenme_fee', models.FloatField()),
                ('is_funded', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.loanoffer')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.requestedloan')),
            ],
        ),
    ]
