# Generated by Django 4.0.1 on 2022-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_loan_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanoffer',
            name='annual_interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
