# Generated by Django 3.2.11 on 2022-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_loanoffer_annual_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='number_of_payments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
