# Generated by Django 3.2.11 on 2022-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220123_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='payment_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_number_of_payments',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
